name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        openssl: [off]
        include:
          - os: ubuntu-latest
            openssl: on

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: make build dir
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure cmake
      run: cmake -S ${{ github.workspace }} -B ${{runner.workspace}}/build -DUSE_OPENSSL=${{ matrix.openssl }}
    - name: build 
      run: cmake --build ${{runner.workspace}}/build 
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest -VV --no-compress-output -T Test
    - name: upload test report
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-TestReport
        path: ${{runner.workspace}}/build/Testing/*/Test.xml
