name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-10.15
          - windows-latest
        openssl: [off]
        include:
          - os: ubuntu-latest
            openssl: on

    steps:
    - name: Install tools
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt install -y valgrind

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: make build dir
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure cmake
      run: cmake -S ${{ github.workspace }} -B ${{runner.workspace}}/build -DUSE_OPENSSL=${{ matrix.openssl }}
    - name: build 
      run: cmake --build ${{runner.workspace}}/build

    - name: test
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --target run-tests
      env:
        UM_TEST_DEBUG: 7

    - name: Memory Check
      working-directory: ${{runner.workspace}}/build
      if: always() && matrix.os == 'ubuntu-latest'
      run: ctest --no-compress-output -T MemCheck
      env:
        UM_TEST_DEBUG: 7

    - name: upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-TestReport
        path: ${{runner.workspace}}/build/Testing/
