name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - name: make build dir
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure cmake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
    - name: build 
      run: cmake --build ${{runner.workspace}}/build 
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest -VV --no-compress-output 
